#ifndef CONFIG
#define CONFIG

#define CONFIG_GPIO_BUTTON_PIN 0
#define CONFIG_GPIO_LED_PIN 33

#define CONFIG_GPIO_LED_ON 0
#define CONFIG_GPIO_LED_OFF 1

#define CONFIG_WIFI_SSID "SSID"
#define CONFIG_WIFI_PASSWORD "PASSWORD"

#define CONFIG_SD_MOUNT_POINT "/sdcard"
#define CONFIG_SD_1_LINE true

#define CONFIG_OUTPUT_FILE "REDUCED_DATA.csv"

#define CONFIG_SNIFFER_TASK_STACK_SIZE 4096
#define CONFIG_SNIFFER_TASK_PRIORITY 2
#define CONFIG_SNIFFER_WORK_QUEUE_LEN 128

#endif