#ifndef CONFIG
#define CONFIG

#define CONFIG_GPIO_BUTTON_PIN 0
#define CONFIG_GPIO_LED_PIN 33

#define CONFIG_GPIO_LED_ON 0
#define CONFIG_GPIO_LED_OFF 1

#define CONFIG_WIFI_SSID "SSID"
#define CONFIG_WIFI_PASSWORD "PASSWORD"

#define CONFIG_SD_MOUNT_POINT "/sdcard"
#define CONFIG_SD_1_LINE true

#define CONFIG_PCAP_FILENAME_MASK "file_%06d.pcap"


#define CONFIG_SAVE_FREQUENCY_MINUTES 30

#endif